name: unit_tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Tests
        run: |
          pip install pytest pytest-cov
          pytest tests --junitxml=junit/test-results.xml --cov=cosipy --cov-report=xml --cov-report=html
      - name: Codecov
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}            